global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'hhhomes-erp'
    environment: 'production'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/alerts/*.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'hhhomes-server'

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Blue API instance
  - job_name: 'api-blue'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-blue:3001']
        labels:
          service: 'api'
          deployment: 'blue'

  # Green API instance
  - job_name: 'api-green'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-green:3001']
        labels:
          service: 'api'
          deployment: 'green'

  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
